######################### General properties #########################
aref_trim: 30
order: 1
out_path: derivatives/EEG-IP-L
ref_loc_file: derivatives/EEG-IP-L/code/misc/standard_1020_ll_ref19.elc
save_f_res: 1
sd_t_pad: 1
in_path: []
montage_info: [0.0, -16.0, 0.0, -0.02, 0.0, -1.58, 10.7, 11.5, 11.5]


################## General info about the project ####################
project:
  readme: '# Q1K ACAR Dataset'

  # Montage use to make file BIDS compliant.
  # Can be path to digitized montage OR a string of one of mne's built in standard montages as specified by mne.channels.get_builtin_montages().
  # Can be left empty if the input dataset is already in BIDS format.
  bids_montage: GSN-HydroCel-129

  # montage used while running the lossless pipeline.
  # if empty, the pipeline will use the electrodes.tsv sidecar file, if created during the BIDS conversion.
  # If specified, needs to be a string of one of mne's built in standard montages.
  analysis_montage: ''
  
  set_montage_kwargs: {}

  coordsys:
    EEGCoordinateSystem: Other
    EEGCoordinateUnits: metres
    
  general_info:
    authors: [Q1K Neuroimaging group]
    institution_Name: McGill University
    institution_address: 3775 Rue University, Montreal, QC
    dataset_doi: []
    funding: Azrieli Foundationt
    how_to_acknowledge: tba
    license: ''
    name: Q1K Mismatched Negativity
    references_and_links: []

  t_info:
    EEG_placement_scheme: EGI 129
    cap_manufacturer: EGI
    cap_manufacturers_model_name: Hydrocel 129 Channel
    hardware_filters: n/a
    manufacturer: Electrical Geodesics
    manufacturers_model_name: NetAmps300
    power_line_frequency: 60
    software_filters: n/a
    software_versions: NetStation V4.5
    
######################## Task break detection ########################
# See arguments definition from mne.preprocessing.annotate_breaks
find_breaks:

############################## epoching ##############################
epoching:
  overlap: 0
  
  # See arguments definition from mne.Epochs
  epochs_args:
    baseline: null
    tmax: 1
    tmin: 0


########################### EEG filtering ############################
# See arguments definition from mne.io.Raw.filter & mne.io.Raw.notch_filter
filtering:
  filter_args:
    h_freq: 100
    l_freq: 1
  notch_filter_args:
    freqs: []


############################## SLURM #################################
# Options for running the pipeline on a cluster
# through SLURM
slurm_options:
  account: def-emayada
  job_name: pylossless
  memory: 16g
  mpi: false
  num_tasks: 1
  program_options: []
  threads_per_task: []
  time_limit: 2h


################################ ICA #################################
ica:
  ic_ic_sd:
    flag_crit: 0.2
    flag_method: fixed
    flag_vals: null
    init_crit: 6
    outlier_method: q
    init_vals: [0.3, 0.7]

  # See arguments definition from mne.preprocessing.ICA
  ica_args:
    run1:
      method: fastica
    run2:
      method: infomax
      fit_params:
        extended: True


########################## Nearest neigbhor ##########################
nearest_neighbors:
  n_nbr_ch: 3
  n_nbr_epoch: 3
  

####################### Pipeline steps config ########################
bridge:
  bridge_trim: 40
  bridge_z: 6

ch_ch_sd:
  flag_crit: 0.2
  flag_method: fixed
  flag_vals: []
  init_crit: 16
  outlier_method: q
  init_vals: [0.3, 0.7]

ch_low_r:
  flag_crit: 0.2
  flag_method: fixed
  flag_vals: []
  init_crit: 16
  outlier_method: q
  init_vals: [0.3, 0.7]

epoch_ch_sd:
  flag_crit: 0.2
  flag_method: fixed
  flag_vals: []
  init_crit: 16
  outlier_method: q
  init_vals: [0.3, 0.7]

epoch_gap:
  min_gap_ms: 2000

epoch_low_r:
  flag_crit: 0.2
  flag_method: fixed
  flag_vals: []
  init_crit: 16
  outlier_method: q
  init_vals: [0.3, 0.7]
